services:
    opencrate_dev:
        build:
            context: .
            dockerfile: Dockerfile
        image: opencrate-dev:latest
        container_name: opencrate_dev
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [ gpu ]
        volumes:
            - ./:/home/opencrate/
            - /var/run/docker.sock:/var/run/docker.sock
        command: zsh -c "tail -f /dev/null"
        entrypoint: /root/.hooks/container-first-startup.sh
        environment:
            - GIT_USER_NAME=${HOST_GIT_NAME}
            - GIT_USER_EMAIL=${HOST_GIT_EMAIL}
