name: Unit Test Docker

# This workflow is triggered after the 'Build and Push Docker' workflow completes successfully.
# It can also be triggered manually.
on:
  workflow_run:
    workflows: ["Build and Push Docker"] # The name of your build workflow
    types:
      - completed
  workflow_dispatch:
    inputs:
      version:
        description: 'The image tag to test (e.g., v1.2.3 or main)'
        required: true
        default: 'main'

jobs:
  # This gatekeeper job ensures we only run tests on successful builds.
  trigger-tests:
    name: Trigger Tests
    runs-on: ubuntu-latest
    # For workflow_run, only proceed if the build workflow succeeded.
    # For workflow_dispatch, always proceed.
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Log Trigger Event
        run: echo "Build workflow succeeded. Triggering test matrix."

  test-images:
    name: Test ${{ matrix.os }} / ${{ matrix.runtime }} / py${{ matrix.python_version }}
    needs: trigger-tests
    runs-on: ${{ matrix.os }} # Run on the OS defined in the matrix
    strategy:
      fail-fast: false # Ensure all tests run even if one fails
      matrix:
        os: [ubuntu-latest, windows-latest]
        runtime: [cpu, cuda]
        python_version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
        # IMPORTANT: Exclude impossible combinations
        exclude:
          # GitHub's Windows runners do not have NVIDIA GPUs, so CUDA tests cannot run.
          - os: windows-latest
            runtime: cuda

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine Version to Test
        id: get_version
        # If triggered by a build, use the build's tag. If triggered manually, use the input.
        run: |
          if [[ "${{ github.event_name }}" == "workflow_run" ]]; then
            echo "VERSION=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          fi

      - name: Login to Docker Hub (optional but good practice)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Docker Container Test
        shell: bash # Ensure bash is used on both Ubuntu and Windows for script consistency
        run: |
          make docker-test \
            RUNTIME=${{ matrix.runtime }} \
            PYTHON_VERSION=${{ matrix.python_version }} \
            VERSION=${{ steps.get_version.outputs.VERSION }}

      - name: Upload Test Logs on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failed-test-logs-${{ matrix.os }}-${{ matrix.runtime }}-py${{ matrix.python_version }}
          path: tests/logs/